# Site
repository: NikooMoradi/nikoomoradi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nikou Moradi
title: 
email: nikoomoradi81@gmail.com
website: nikoomoradi.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: 
github_username:  NikooMoradi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: nikoo-moradi
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPEG
about_content: | # this will include new lines to allow paragraphs
  Hello there! I'm Nikou Moradi, an Electrical Engineering undergraduate student, entering my last semester at Sharif University of Technology. I'm on track to graduate by july 2025, and I've used these formative years to delve deep into various facets of Computer Science and Electrical Engineering. My primary research interests include <mark>Medical Image Analysis</mark>, <mark>Neuroscience/mark>, and <mark>applications of AI in healthcare</mark>. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: EEG Signal Analysis for Pattern Recognition
        # link: github.com/NikooMoradi
        # link_text: Project Website
        additional_links:
          - title:  github.com/NikooMoradi
            icon: fab fa-github
            url: https://github.com/NikooMoradi/Patter-Recognition-Issue-EEG-Signals-
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          My AI and Biological Computation course project
        description: | # this will include new lines to allow paragraphs
              In this project, we aimed to investigate the impact of feature extraction and selection on the performance of multilayer perceptron (MLP) and radial basis function (RBF) neural networks. We utilized time and frequency domain features of EEG signals, normalized and initially selected through Fisher score, and further optimized by a Particle Swarm Optimization (PSO) algorithm. Training both networks with these selected features under 5-fold cross-validation, we compared the outcomes to highlight the PSO algorithm’s efficiency in refining feature selection. This approach demonstrated the importance of targeted feature selection in improving neural network accuracy, offering a valuable strategy for future AI applications in complex data analysis scenarios.
      - layout: top-middle
        title: Analysis of Phase Locking Value during Olfactory Stimulation as a Biomarker for Alzheimers Disease in EEG Signals
        # link: github.com/NikooMoradi
        # link_text: Project Website
        additional_links:
          - title:  github.com/NikooMoradi
            icon: fab fa-github
            url: https://github.com/NikooMoradi/Analysis-of-PLV-during-Olfactory-Stimulation
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          My Signals and Systems course project
        description: | # this will include new lines to allow paragraphs
          In this project, I investigated Phase Locking Value(PLV) and other phase amplitude coupling metrics as a biomarker for Alzheimers Disease. 
      # - layout: top-middle
      #   title: Offline Social Media
      #   # link: github.com/NikooMoradi
      #   # link_text: Project Website
      #   additional_links:
      #     - title:  github.com/NikooMoradi
      #       icon: fab fa-github
      #       url: https://github.com/NikooMoradi/Offline-Social-Media
      #     # - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #     #   icon: fab fa-github
      #     #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      #   quote: >
      #     My Object Oriented Programming course project
      #   description: | # this will include new lines to allow paragraphs
      #     This project is a simulated offline social media, inspired by Twitter, which offers both personal and business accounts for sharing tweets, photos, and engaging with others, using Java and SQL, as well as swing for graphics.
      # - layout: top-middle
      #   title: Head Football (NS version)
      #   # link: github.com/NikooMoradi
      #   # link_text: Project Website
      #   additional_links:
      #     - title:  github.com/NikooMoradi
      #       icon: fab fa-github
      #       url: https://github.com/NikooMoradi/Head-Footbal
      #     # - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #     #   icon: fab fa-github
      #     #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      #   quote: >
      #     My Basic Programming course project
      #   description: | # this will include new lines to allow paragraphs
      #     This project, inspired by the game Head Football LaLiga Soccer, is a fun and interactive game developed as part of a computer programming course at SUT. The game features graphical animations created using SDL 2, a popular multimedia library for C++.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sharif University of Technology
        caption: 2021 - 2025 (expected)
        sub_title: BSc in Electrical Engineering
        quote: >
        # Established in 1966 with the aim of training and providing some of the specialized personnel needed in the country, at high scientific levels. Fortunately, during its activity, it has been able to establish itself as a leading scientific institute in industry, modern technologies and applied sciences in the field of science, regionally and globally.     
        description: | # this will include new lines to allow paragraphs
          During my past four years at Sharif, I've gained invaluable experience and knowledge, both in academia and life. I've significantly enhanced my key skills, including teamwork and meeting tight deadlines. Every moment at Sharif has been thoroughly enjoyable, and I eagerly anticipate what lies ahead.

          I spend a lot of my free time participating in Resana Association activities, which include hosting events and serving as a staff member for various occasions.

      - layout: left
        title: Farzanegan Amin High School
        caption: 2018 - 2021
        sub_title: Diploma in Mathematics and Physics    
        description: | # this will include new lines to allow paragraphs
          High school was where I laid the groundwork for my academic path. It's where I learned about teamwork, time management, and handling pressure. Fond memories and the importance of work-life balance were part of the package.

          Besides hitting the books, I was a memeber of Badminton and Basketball team and I actively participated in Art Competitions.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electrical engineering some of my other interests and hobbies are:
      - Arts
      - Sports
      - Hosting events
# - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
